### ISSUE TITLE
The value returned by function f() which is used for calculating factorial is not working.

### ISSUE THREAD

**Issue by ruthvikbobbili** [Viswanadh-Kavuri/SE_Bonus_Project#5]
When trying to calculate factorial for 0, the method is returning 0 instead of 1.

**Comment by Viswanadh-Kavuri** [comment]
Issue with factorial calculation for 0 and 1 is resolved.

**Comment by ruthvikbobbili** [comment]
Now it is not working for other numbers, can you please check the JavaScript code for other numbers?

**Comment by Viswanadh-Kavuri** [comment]
reopening the issue to resolve factorial issue as reported by @ruthvikbobbili

**Comment by Viswanadh-Kavuri** [comment]
no issues with factorial calculation.
